8278041: riscv: Use t2 as the dedicated machine flags register in C2
openjdk/riscv-port pull request #21
Opened 2021-12-01 07:56 UTC by yadongw

There are non-allocatable registers t0 and t1 in C2, frequently used as temporary registers for common code snipptes. Meanwhile, C2 use t1 as the flags register, so that many instructs using t1 as a temporary register must declare the data flow effect of t1 which is not part of a match rule. So we can reserve t2 and use it as the machine flags register in C2 instead, to reduce the probability of misuse of t1 without declaring the data flow effect.

2021-12-01 08:36 UTC, RealFYang commented
This will surely make the code more maintainable. Nice cleanup :-)
No obvious performance impact is witnessed by running specjbb2015 with 't2' used as the dedicate C2 machine flags register.

2021-12-01 09:07 UTC, RealFYang requested changes
Looks like we missed instructs like: decodeKlass_not_null_with_tmp, string_indexofUU, etc. ? Maybe you can search "rFlagsReg tmp" to find.

2021-12-01 13:11 UTC, kuaiwei commented
Hi Yadong, it looks cost too much to reserve a dedicated register for control flag. I think in most cases we can use the 2 scratch registers instead. Can you show some complicated cases? We can check if they can be rewrite to avoid the complication.

2021-12-02 04:02 UTC, RealFYang commented
> Hi Yadong, it looks cost too much to reserve a dedicated register for control flag. I think in most cases we can use the 2 scratch registers instead. Can you show some complicated cases? We can check if they can be rewrite to avoid the complication.

Well, I think there might be some tradeoff here. 
On the one hand, use the same register 't1' for two different purposes (scratch register & flags registers) at the same time looks rather error prone as mentioned in the PR description. 
On the other hand, use another register 't2' as the dedicated flags register could somehow affect the performance in certain cases even though this is not reflected on the specjbb2015 numbers. 
Personally, I have no obvious bias here. I would like to hear how the other Reviewers would say about this. Maybe @shipilev ?
Thanks.

2021-12-02 13:04 UTC, yadongw commented
> > Hi Yadong, it looks cost too much to reserve a dedicated register for control flag. I think in most cases we can use the 2 scratch registers instead. Can you show some complicated cases? We can check if they can be rewrite to avoid the complication.
> 
> Well, I think there might be some tradeoff here. On the one hand, use the same register 't1' for two different purposes (scratch register & flags registers) at the same time looks rather error prone as mentioned in the PR description. On the other hand, use another register 't2' as the dedicated flags register could somehow affect the performance in certain cases even though this is not reflected on the specjbb2015 numbers. Personally, I have no obvious bias here. I would like to hear how the other Reviewers would say about this. Maybe @shipilev ? Thanks.

Agree. it's a tradeoff. There may be more spill/unspills in some scenarios of a high register pressue, but it is more friendly for code scheduling and higher maintainability with less data flow effects. By the way, we found this PR did not affect the performance of SPECjvm2008 on unmatched.

2021-12-02 13:06 UTC, yadongw commented
> Hi Yadong, it looks cost too much to reserve a dedicated register for control flag. I think in most cases we can use the 2 scratch registers instead. Can you show some complicated cases? We can check if they can be rewrite to avoid the complication.

All instructs that remove the rFlagsReg operand are implicitly use t1.

2021-12-09 12:30 UTC, kuaiwei commented
> > > Hi Yadong, it looks cost too much to reserve a dedicated register for control flag. I think in most cases we can use the 2 scratch registers instead. Can you show some complicated cases? We can check if they can be rewrite to avoid the complication.
> > 
> > 
> > Well, I think there might be some tradeoff here. On the one hand, use the same register 't1' for two different purposes (scratch register & flags registers) at the same time looks rather error prone as mentioned in the PR description. On the other hand, use another register 't2' as the dedicated flags register could somehow affect the performance in certain cases even though this is not reflected on the specjbb2015 numbers. Personally, I have no obvious bias here. I would like to hear how the other Reviewers would say about this. Maybe @shipilev ? Thanks.
> 
> Agree. it's a tradeoff. There may be more spill/unspills in some scenarios of a high register pressue, but it is more friendly for code scheduling and higher maintainability with less data flow effects. By the way, we found this PR did not affect the performance of SPECjvm2008 on unmatched:
> 
> before：
> 
> ```
> compress                      17.71
> crypto                        24.16
> derby                         32.39
> mpegaudio                     14.68
> scimark.large                 3.65
> scimark.small                 15.07
> serial                        12.08
> startup                       3.88
> sunflow                       7.21
> ```
> 
> after:
> 
> ```
> compress                      17.74
> crypto                        24.1
> derby                         32.67
> mpegaudio                     14.64
> scimark.large                 3.67
> scimark.small                 15.42
> serial                        12.98
> startup                       3.6
> sunflow                       7.09
> ```

Hi Yadong,
  Thanks for the test. Since benchmark score showed little impact so far. I'm fine to use a dedicated register now. But it still looks too many special registers in riscv. I think it can be improved in future.

2021-12-10 09:28 UTC, RealFYang commented
Let's keep the current implementation for some time to see :-)

2021-12-14 09:19 UTC, yadongw commented
I'll close this pr first, and reopen later if needed.

2021-12-14 09:19 UTC, yadongw commented
I'll close this pr first, and reopen later if needed.

2021-12-14 09:19 UTC, closed without merging