8280497: riscv: Undefined Behaviour in class Assembler
openjdk/riscv-port pull request #53
Opened 2022-01-26 05:28 UTC by yadongw

The same problem exists on the riscv platfom. So we follow https://bugs.openjdk.java.net/browse/JDK-8276563.
```
All instances of type Register exhibit UB in the form of wild pointer (including null pointer) dereferences. This isn't very hard to fix: we should make Registers pointer to something rather than aliases of small integers.
```
Hotspot/jdk tier1 were passed on the unmatched board. And all jtreg tests have been tested on Qemu without new failures.

2022-01-26 06:25 UTC, RealFYang requested changes

2022-01-26 06:25 UTC, RealFYang commented on src/hotspot/cpu/riscv/assembler_riscv.hpp
>      n_int_register_parameters_j   = 8, // x11, ... x17, x10 (rj_rarg0, j_rarg1, ...)
Could you please also fix this typo: "rj_rarg0" should be "j_rarg0"? Otherwise looks good. Thanks.

2022-01-26 07:00 UTC, RealFYang approved these changes

2022-01-26 11:07 UTC, feilongjiang approved these changes

2022-01-27 01:42 UTC, yadongw commented
/integrate

2022-01-27 01:43 UTC, closed without merging